### ISSUE TITLE
PowerHub

### ISSUE THREAD

**Issue by ktsukamoto01** [SouthEugeneRoboticsTeam/InfiniteRecharge-2020#11]
2 Intake motors, each follower, running both directions
1 motor to control flappers separate subsystem (flappers and intake can run at same time)

**Comment by will-hou** [comment]
~~We'll also have a beam break (two sensors that send out a beam of light to each other and signals when the beam is "broken") at the foot of the intake. Might be cool to try and count how many power cells are currently in the robot using it~~

Scratch that... there is no beam break

**Comment by gnawinganimal** [comment]
This is done 👍
