### ISSUE TITLE
Don't set up ktlint

### ISSUE THREAD

**Issue by gnawinganimal** [SouthEugeneRoboticsTeam/InfiniteRecharge-2020#15]
ktlint is trash

**Comment by gnawinganimal** [comment]
Sorry that was kind of vague
So we should have ktlint on master because the final version of our code should be neat, but on all the other branches ktlint will just slow down development.

**Comment by will-hou** [comment]
Could we have ktlint run as a github action on branch pushes? That way we can have pretty code without slowing down development?

This could be a possible option: https://github.com/marketplace/actions/kotlin-linter

**Comment by gnawinganimal** [comment]
That would be a good idea, but I think we should have a way to do it from gradle too because we want to be able to do it from our local machine

**Comment by will-hou** [comment]
Let's discuss on #9 since we'll still be adding it then
