### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by will-hou** [SouthEugeneRoboticsTeam/InfiniteRecharge-2020#3]
Let's log some stuff to Network Tables after we've gotten some subsystems made.
![source](https://user-images.githubusercontent.com/23201789/72211055-3d28e980-3479-11ea-9940-9d2c52b0a09f.gif)

**Comment by mckelveygreg** [comment]
Did we do this in deep space? Like is there an example to show new programmers?

**Comment by will-hou** [comment]
[Yes](https://github.com/SouthEugeneRoboticsTeam/DeepSpace-2019/blob/development/src/main/kotlin/org/sert2521/deepspace/util/Telemetry.kt) but I believe there's a [specific way to do it with Sertain](https://github.com/SouthEugeneRoboticsTeam/sertain/pull/38) now that is different from what we did last year. 

If I recall correctly, we did have a telemetry branch in the BunnyBots repo that was accidentally deleted locally before it could get pushed so there is no example code currently. 

@Jamdan2 How hard would it to be to write some very basic telemetry code with Sertain in the BunnyBots repo? Could be something as simple as displaying drivetrain encoder values maybe. If we had that as an example people could refer to it and add in telemetry stuff as they're writing their subsystems.

I actually don't know how telemetry works in sertain myself and would love an example too 😅

**Comment by gnawinganimal** [comment]
Sure! To link a value to network tables just use `linkTableEntry`:
```kotlin
class Arm : Subsystem("Arm") {
	val motor = MotorController(TalonId(0))
	
	init {
		RobotScope.linkTableEntry("Position", name) { motor.position }
	}
}
```

**Comment by mckelveygreg** [comment]
Now, can we walk for volunteers to self assign and submit a pr? And put a
good tag on this issue, like good first or or something?

**Comment by will-hou** [comment]
Oh sweet! Had no idea it was that simple. Thanks for writing up an example.

Could we just tell each group to incorporate telemetry into their subsystem and make sure they did it during code reviews? This way we can just close the issue. I originally thought we needed to write a class or something but it looks like that isn't the case.

**Comment by mckelveygreg** [comment]
Oh that seems like a good idea!
Perhaps make a pr template people can follow?

**Comment by mckelveygreg** [comment]
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by will-hou** [comment]
Huh didn't know you could make PR templates -- that's pretty neat.

We had something called sertbot that would[ reply to PR with a list of things that should happen](https://github.com/SouthEugeneRoboticsTeam/DeepSpace-2019/pull/8) before it gets merged.  Maybe we could enable that and add some sort of template as well? I'm not currently thinking of anything that's general enough (and not included already in sertbot) to put in a template that goes on _every_ single PR though. 

Any ideas?
