### ISSUE TITLE
Climber

### ISSUE THREAD

**Issue by ktsukamoto01** [SouthEugeneRoboticsTeam/InfiniteRecharge-2020#4]
either 1 or 2 motors on each arm
separate motors and buttons per arm
motor that retracts string

**Comment by ktsukamoto01** [comment]
one motor that spins the string in

**Comment by ktsukamoto01** [comment]
one motor that goes both ways with a joystick

**Comment by ktsukamoto01** [comment]
One motor for the pulley manually on the joystick spinning both directions
Two motors for the wench coded the same as each other with button

**Comment by ktsukamoto01** [comment]
add each follower code to the 2 motors for the wench

**Comment by ktsukamoto01** [comment]
put winch and lift on the same subsystem

**Comment by will-hou** [comment]
Resolved by #18. Thanks @ktsukamoto01 , @Jamdan2 , and @kturner44 !
